 - name: create target group
     elb_target_group:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       name: poctg
       state: present
       region: "{{ aws_region }}c"
       protocol: http
       port: 80
       vpc_id: "{{ my_vpc.vpc.id }}"
     register: app_tg
   - name: launch load balancer
     ec2_elb_lb:
       name: "{{ app_elb_name }}"
       region: "{{ aws_region }}"
       state: present
       subnets:
        - 192.168.1.0/28
        - 192.168.1.16/28
       zones: "{{ aws_region }}c"
       security_group_ids: "{{ SG_results.group_id }}"
       connection_draining_timeout: 60
       aws_access_key:   "{{ aws_access_key }}"
       aws_secret_key:   "{{ aws_secret_key }}"
       listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
       healthy_threshold: 5
     tags: load_balancer

   - name: create launch config
     ec2_lc:
       name: "{{ app_lc_name }}"
       image_id: "{{ image_id }}"
       key_name: "{{ my_key }}"
       region: "{{ aws_region }}"
       security_groups: "{{ SG_results.group_id }}"
       instance_type: "t2.micro"
       # user_data: "{{ user_data }}"
     tags: launch_config

   - name: create autoscale groups
     ec2_asg:
       name: "{{ app_asg_name }}"
       load_balancers: "{{ app_elb_name }}"
       launch_config_name: "{{ app_lc_name }}"
       min_size: 1
       max_size: 2
       #desired_capacity: "{{ desired_capacity }}"
       region: "{{ aws_region }}"
       # vpc_zone_identifier: "{{  }}"
       health_check_type: EC2
       health_check_period: 300

   - name: create scale down  policy
     ec2_scaling_policy:
       state: present
       region: "{{ aws_region }}"
       name: scale-down-policy
       adjustment_type: ChangeInCapacity
       asg_name: "{{ app_asg_name }}"
       scaling_adjustment: -1
       min_adjustment_step: -1
       cooldown: 300
     register: scale_down_policy
     tags: scaling_policy

   - name: create scale up policy
     ec2_scaling_policy:
       state: present
       region: "{{ aws_region }}"
       name: scale-up-policy
       adjustment_type: ChangeInCapacity
       asg_name: "{{ app_asg_name }}"
       scaling_adjustment: 1
       min_adjustment_step: 1
       cooldown: 300
       register: scale_up_policy
     tags: scaling_policy

